spring.application.name=userservice
server.port=8083
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE}
spring.app.jwtExpirationMs=${JWT_EXPIRATION_MS}
spring.app.jwtSecret=${JWT_SECRET}
