server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://host.docker.internal:8083
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users(?<segment>/.*), /${segment}

        - id: businesses-service
          uri: http://host.docker.internal:8080
          predicates:
            - Path=/businesses/**
          filters:
            - RewritePath=/businesses(?<segment>/.*), /${segment}

        - id: audits-service
          uri: http://host.docker.internal:8081
          predicates:
            - Path=/audits/**
          filters:
            - RewritePath=/audits(?<segment>/.*), /${segment}

        - id: rulesets-service
          uri: http://host.docker.internal:8082
          predicates:
            - Path=/rulesets/**
          filters:
            - RewritePath=/rulesets(?<segment>/.*), /${segment}

        - id: frontend
          uri: http://host.docker.internal:5173
          predicates:
            - Path=/frontend/**
          filters:
            - RewritePath=/frontend(?<segment>/.*), /${segment}

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
